// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using  QuizGame.Models;
//
//    var booster = Booster.FromJson(jsonString);

namespace QuizGame.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Booster
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("boostername")]
        public string Boostername { get; set; }

        [JsonProperty("reset_on_new_game")]
        public long ResetOnNewGame { get; set; }

        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("updated_at")]
        public DateTimeOffset UpdatedAt { get; set; }
    }

    public partial class Booster
    {
        public static Booster FromJson(string json) => JsonConvert.DeserializeObject<Booster>(json, QuizGame.Models.Converter.Settings);
    }

}
